# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymenu',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'блюдо', 'verbose_name_plural': 'блюда'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuApp.CategoryMenu', verbose_name='категория блюда'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descr',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='isToday',
            field=models.BooleanField(verbose_name='сегодня в меню'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(verbose_name='цена'),
        ),
    ]
