# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-03 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0002_auto_20161003_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Dish',
        ),
    ]
