# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0003_auto_20161003_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymenu',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
