# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-30 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0004_categorymenu_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymenu',
            options={'ordering': ['order'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='фото блюда'),
        ),
    ]
