# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-03 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161002_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryNews',
        ),
        migrations.DeleteModel(
            name='New',
        ),
    ]
