# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_basicdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='basicdata',
            name='contact_text',
            field=models.TextField(verbose_name='\u0442\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u043d\u0430\u043f\u0438\u0448\u0438\u0442\u0435 \u043d\u0430\u043c'),
        ),
    ]
