# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-30 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст к фото если нужен')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='фото')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsApp.New', verbose_name='фото относится к этой нвоости \\ событию')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
