# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_new_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_photos',
            name='isDefault',
            field=models.BooleanField(default=0, verbose_name='обложка альбома'),
            preserve_default=False,
        ),
    ]
